const B01 = {
  configFormatTableAsset: [
    {
      label: "A. TÀI SẢN NGẮN HẠN",
      code: "100",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "I. Tiền và các khoản tương đương tiền",
      code: "110",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Tiền",
      code: "111",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Các khoản tương đương tiền",
      code: "112",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },

    {
      label: "II. Đầu tư tài chính ngắn hạn",
      code: "120",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Chứng khoán kinh doanh",
      code: "121",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Dự phòng giảm giá chứng khoán kinh doanh (*)",
      code: "122",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Đầu tư nắm giữ đến ngày đáo hạn",
      code: "123",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },

    {
      label: "III. Các khoản phải thu ngắn hạn",
      code: "130",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Phải thu ngắn hạn của khách hàng",
      code: "131",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Trả trước cho người bán ngắn hạn",
      code: "132",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "3. Phải thu nội bộ ngắn hạn",
      code: "133",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "4. Phải thu theo tiến độ kế hoạch hợp đồng xây dựng",
      code: "134",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "5. Phải thu về cho vay ngắn hạn",
      code: "135",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "6. Phải thu ngắn hạn khác",
      code: "136",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "7. Dự phòng các khoản phải thu ngắn hạn khó đòi (*)",
      code: "137",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "8. Tài sản thiếu chờ xử lý",
      code: "139",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "IV. Hàng tồn kho",
      code: "140",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "1. Hàng tồn kho",
      code: "141",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Hàng mua đang đi trên đường",
      code: "141A",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Nguyên liệu, vật liệu tồn kho",
      code: "141B",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Công cụ, dụng cụ trong kho",
      code: "141C",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: " - Chi phí SXKD dở dang",
      code: "141D",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Thành phẩm tồn kho",
      code: "141E",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Hàng hóa tồn kho",
      code: "141F",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: " - Hàng hoá kho bảo thuế",
      code: "141G",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: " - Hàng gửi đi bán",
      code: "141H",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Dự phòng giảm giá hàng tồn kho (*)",
      code: "149",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "V. Tài sản ngắn hạn khác",
      code: "150",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "1. Chi phi trả trước ngắn hạn",
      code: "151",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Thuế giá trị gia tăng được khấu trừ",
      code: "152",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Thuế và các khoản khác phải thu Nhà nước",
      code: "153",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "4. Giao dịch mua bán lại trái phiếu Chính phủ",
      code: "154",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "5. Tài sản ngắn hạn khác",
      code: "155",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "B. TÀI SẢN DÀI HẠN",
      code: "200",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "I. Các khoản phải thu dài hạn",
      code: "210",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "1. Phải thu dài hạn của khách hàng",
      code: "211",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Trả trước cho người bán dài hạn",
      code: "212",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Vốn kinh doanh ở công ty trực thuộc",
      code: "213",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "4. Phải thu nội bộ dài hạn",
      code: "214",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "5. Phải thu về cho vay dài hạn",
      code: "215",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "6. Phải thu dài hạn khác",
      code: "216",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "7. Dự phòng phải thu dài hạn khó đòi (*)",
      code: "219",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },

    {
      label: "II. Tài sản cố định",
      code: "220",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Tài sản cố định hữu hình",
      code: "221",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "222",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "223",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "2. Tài sản cố định thuê tài chính",
      code: "224",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "225",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "226",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Tài sản cố định vô hình",
      code: "227",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "228",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "229",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "III. Bất động sản đầu tư",
      code: "230",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "231",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "232",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "IV. Tài sản dở dang dài hạn",
      code: "240",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "1. Chi phí sản xuất, kinh doanh dở dang dài hạn",
      code: "241",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Chi phí xây dựng cơ bản dở dang",
      code: "242",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "V. Đầu tư tài chính dài hạn",
      code: "250",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "1. Đầu tư vào công ty con",
      code: "251",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Đầu tư vào công ty liên doanh, liên kết",
      code: "252",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Đầu tư góp vốn vào công ty khác",
      code: "253",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "4. Dự phòng đầu tư tài chính dài hạn (*)",
      code: "254",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "5. Đầu tư nắm giữ đến ngày đáo hạn",
      code: "255",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "VI. Tài sản dài hạn khác",
      code: "260",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Chi phí trả trước dài hạn",
      code: "261",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "2. Tài sản thuế thu nhập hoãn lại",
      code: "262",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Thiết bị, vật tư, phụ tùng thay thế dài hạn",
      code: "263",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "4. Tài sản dài hạn khác",
      code: "268",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "TỔNG CỘNG TÀI SẢN (270 = 100 + 200)",
      code: "270",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
  ],

  configFormatTableInvestment: [
    {
      label: "C. NỢ PHẢI TRẢ",
      code: "300",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "I. Nợ ngắn hạn",
      code: "310",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Phải trả người bán ngắn hạn",
      code: "311",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Người mua trả tiền trước ngắn hạn",
      code: "312",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Thuế và các khoản phải nộp nhà nước",
      code: "313",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "4. Phải trả người lao động",
      code: "314",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "5. Chi phí phải trả ngắn hạn",
      code: "315",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "6. Phải trả nội bộ ngắn hạn",
      code: "316",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "7. Phải trả theo tiến độ kế hoạch hợp đồng xây dựng",
      code: "317",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "8. Doanh thu chưa thực hiện ngắn hạn",
      code: "318",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "9. Phải trả ngắn hạn khác",
      code: "319",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "10. Vay và nợ thuê tài chính ngắn hạn",
      code: "320",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "11. Dự phòng phải trả ngắn hạn",
      code: "321",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "12. Quỹ khen thưởng, phúc lợi",
      code: "322",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "13. Quỹ bình ổn giá",
      code: "323",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "14. Giao dịch mua bán lại trái phiếu Chính phủ",
      code: "324",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "II. Nợ dài hạn",
      code: "330",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Phải trả người bán dài hạn",
      code: "331",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Người mua trả tiền trước dài hạn",
      code: "332",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Chi phí phải trả dài hạn",
      code: "333",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "4. Phải trả nội bộ về vốn kinh doanh",
      code: "334",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "5. Phải trả nội bộ dài hạn",
      code: "335",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "6. Doanh thu chưa thực hiện dài hạn",
      code: "336",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "7. Phải trả dài hạn khác",
      code: "337",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "8. Vay và nợ thuê tài chính dài hạn",
      code: "338",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "9. Trái phiếu chuyển đổi",
      code: "339",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "10. Cổ phiếu ưu đãi",
      code: "340",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "11. Thuế thu nhập hoãn lại phải trả",
      code: "341",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "12. Dự phòng phải trả dài hạn",
      code: "342",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "13. Quỹ phát triển khoa học, công nghệ",
      code: "343",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "D. VỐN CHỦ SỞ HỮU",
      code: "400",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "I. Vốn chủ sở hữu",
      code: "410",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Vốn góp của chủ sở hữu",
      code: "411",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "- Cổ phiếu phổ thông có quyền biểu quyết",
      code: "411a",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "- Cổ phiếu ưu đãi",
      code: "411b",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Thặng dư vốn cổ phần",
      code: "412",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "3. Quyền chọn chuyển đổi trái phiếu",
      code: "413",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "4. Vốn khác của chủ sở hữu",
      code: "414",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "5. Cổ phiếu quỹ (*)",
      code: "415",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "6. Chênh lệch đánh giá lại tài sản",
      code: "416",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "7. Chênh lệch tỷ giá hối đoái",
      code: "417",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "8. Quỹ đầu tư phát triển",
      code: "418",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "9. Quỹ hỗ trợ sắp xếp doanh nghiệp",
      code: "419",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },

    {
      label: "10. Quỹ khác thuộc vốn chủ sở hữu",
      code: "420",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "11. Lợi nhuận sau thuế chưa phân phối",
      code: "421",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "- LNST chưa phân phối lũy kế đến cuối kỳ trước",
      code: "421a",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: " - LNST chưa phân phối kỳ này",
      code: "421b",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "12. Nguồn vốn đầu tư XDCB",
      code: "422",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: true,
    },
    {
      label: "II. Nguồn kinh phí và quỹ khác",
      code: "430",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "1. Nguồn kinh phí",
      code: "431",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "2. Nguồn kinh phí đã hình thành TSCĐ",
      code: "432",
      isBold: false,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
    {
      label: "TỔNG CỘNG NGUỒN VỐN (440 = 300 + 400)",
      code: "440",
      isBold: true,
      tm: "",
      scn: "",
      sdn: "",
      isBrick: false,
    },
  ],
};

const B02 = [
  {
    label: "1. Doanh thu bán hàng và cung cấp dịch vụ",
    code: "01",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "2. Các khoản giảm trừ doanh thu",
    code: "02",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "3. Doanh thu thuần về bán hàng và cung cấp dịch vụ (10 = 01 - 02)",
    code: "10",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "4. Giá vốn hàng bán",
    code: "11",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },

  {
    label: "5. Lợi nhuận gộp bán hàng và cung cấp dịch vụ (20 = 10 - 11)",
    code: "20",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "6. Doanh thu hoạt động tài chính",
    code: "21",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "7. Chi phí tài chính",
    code: "22",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "- Trong đó: Chi phí lãi vay",
    code: "23",
    isBold: false,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "8. Chi phí bán hàng",
    code: "25",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "9. Chi phí quản lý doanh nghiệp",
    code: "26",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label:
      "10. Lợi nhuận thuần từ hoạt động kinh doanh {30 = 20 + (21 - 22) - (25 + 26)}",
    code: "30",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },

  {
    label: "11. Thu nhập khác",
    code: "31",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "+ Tổng thu nhập khác",
    code: "31A",
    isBold: false,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "+ Thu nhập từ thanh lý, nhượng bán TSCĐ",
    code: "31B",
    isBold: false,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "+ Thu nhập từ thanh lý, nhượng bán TSCĐ (NET)",
    code: "31C",
    isBold: false,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "12. Chi phí khác",
    code: "32",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },

  {
    label: " + Tổng chi phí khác ",
    code: "32A",
    isBold: false,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "+ Chi phí từ thanh lý, nhượng bán TSCĐ",
    code: "32B",
    isBold: false,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "+ Chi phí từ thanh lý, nhượng bán TSCĐ (NET)",
    code: "32C",
    isBold: false,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "13. Lợi nhuận khác (40 = 31 - 32)",
    code: "40",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },

  {
    label: "14. Tổng lợi nhuận kế toán trước thuế (50 = 30 + 40)",
    code: "50",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "15. Chi phí thuế TNDN hiện hành",
    code: "51",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "16. Chi phí thuế TNDN hoãn lại",
    code: "52",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "17. Lợi nhuận sau thuế thu nhập doanh nghiệp (60 = 50 - 51 - 52)",
    code: "60",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },

  {
    label: "18. Lãi cơ bản trên cổ phiếu (*)",
    code: "70",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
  {
    label: "19. Lãi suy giảm trên cổ phiếu (*)",
    code: "71",
    isBold: true,
    tm: "",
    snn: "",
    snt: "",
    isBrick: false,
  },
];

const S06 = [
  {
    stk: "111",
    tkc: "0",
    ttk: "Tiền mặt",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "1111",
    tkc: "111",
    ttk: "Tiền Việt Nam",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "112",
    tkc: "0",
    ttk: "Tiền gửi Ngân hàng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "1121",
    tkc: "112",
    ttk: "Tiền Việt Nam",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "11213",
    tkc: "1121",
    ttk: "Ngân hàng Vietinbank 750",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11214",
    tkc: "1121",
    ttk: "Ngân hàng quân đội MBbank 009",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11215",
    tkc: "1121",
    ttk: "Ngân hàng Maritimebank",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11216",
    tkc: "1121",
    ttk: "Ngân hàng Wooribank 768",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11217",
    tkc: "1121",
    ttk: "Ngân hàng VCB - CN Chương Dương 199",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11218",
    tkc: "1121",
    ttk: "Ngân hàng Techcombank 026",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11219",
    tkc: "1121",
    ttk: "Ngân hàng Sacombank 6668",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "11220",
    tkc: "1121",
    ttk: "Ngân hàng Vietinbank 526",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11221",
    tkc: "1121",
    ttk: "Ngân hàng Wooribank 777",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11227",
    tkc: "1121",
    ttk: "Ngân hàng Sacombank 5688",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "11228",
    tkc: "1121",
    ttk: "Ngân hàng Sacombank 5666",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11229",
    tkc: "1121",
    ttk: "Ngân hàng quân đội MBbank 007",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11230",
    tkc: "1121",
    ttk: "Ngân hàng BIDV 574",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "11231",
    tkc: "1121",
    ttk: "Ngân hàng BIDV 583",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11233",
    tkc: "1121",
    ttk: "Ngân hàng VPbank 749",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11234",
    tkc: "1121",
    ttk: "Ngân hàng Bưu điện Liên Việt",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11235",
    tkc: "1121",
    ttk: "Ngân hàng Vietinbank 930",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "11236",
    tkc: "1121",
    ttk: "Ngân hàng Liên việt 002",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11237",
    tkc: "1121",
    ttk: "Ngân hàng TMCP Tiên Phong VN",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11238",
    tkc: "1121",
    ttk: "Ngân hàng quân đội MBbank 732",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11239",
    tkc: "1121",
    ttk: "Ngân Hàng VIB 176",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11240",
    tkc: "1121",
    ttk: "Ngân hàng Liên việt 003",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11241",
    tkc: "1121",
    ttk: "Ngân hàng Quân Đội 9999",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11242",
    tkc: "1121",
    ttk: "Ngân hàng BIDV 940",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11243",
    tkc: "1121",
    ttk: "Ngân hàng Quân Đội 064",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11244",
    tkc: "1121",
    ttk: "Vietcombank 989",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11245",
    tkc: "1121",
    ttk: "VPbank 098",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11246",
    tkc: "1121",
    ttk: "BIDV 280- Visa",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11247",
    tkc: "1121",
    ttk: "BIDV 241_ Food Ha Dong",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11248",
    tkc: "1121",
    ttk: "BIDV 462_ Holaship",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11249",
    tkc: "1121",
    ttk: "BIDV 557_ Food Linh Đàm",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "11250",
    tkc: "1121",
    ttk: "Ngân hàng VPbank 402",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11251",
    tkc: "1121",
    ttk: "Ngân hàng Vietcombank 404",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11252",
    tkc: "1121",
    ttk: "Ngân hàng Agribank 475",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11253",
    tkc: "1121",
    ttk: "BIDV 252_Food KT",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "11254",
    tkc: "1121",
    ttk: "BIDV 089_Holamart",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "11255",
    tkc: "1121",
    ttk: "Ngân hàng Quốc tế VIB",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "1122",
    tkc: "112",
    ttk: "Ngoại tệ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "112201",
    tkc: "1122",
    ttk: "Ngân hàng Vietcombank 089",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "128",
    tkc: "0",
    ttk: "Đầu tư nắm giữ đến ngày đáo hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "1281",
    tkc: "128",
    ttk: "Đầu tư nắm giữ đến ngày đáo hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "1283",
    tkc: "128",
    ttk: "Cho vay",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "1288",
    tkc: "128",
    ttk: "Các khoản đầu tư khác nắm giữ đến ngày đáo hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "131",
    tkc: "0",
    ttk: "Phải thu của khách hàng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "133",
    tkc: "0",
    ttk: "Thuế GTGT được khấu trừ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "1331",
    tkc: "133",
    ttk: "Thuế GTGT được khấu trừ của hàng hóa, dịch vụ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "138",
    tkc: "0",
    ttk: "Phải thu khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "141",
    tkc: "0",
    ttk: "Tạm ứng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "153",
    tkc: "0",
    ttk: "Công cụ, dụng cụ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "1531",
    tkc: "153",
    ttk: "Công cụ, dụng cụ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "154",
    tkc: "0",
    ttk: "Chi phí sản xuất, kinh doanh dở dang",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "15424",
    tkc: "154",
    ttk: "Chi phí dịch vụ gateway",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "15431",
    tkc: "154",
    ttk: "Chi phí khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "156",
    tkc: "0",
    ttk: "Hàng hóa",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "1561",
    tkc: "156",
    ttk: "Giá mua hàng hóa",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "211",
    tkc: "0",
    ttk: "Tài sản cố định hữu hình",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "2111",
    tkc: "211",
    ttk: "Nhà cửa, vật kiến trúc",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "2112",
    tkc: "211",
    ttk: "Máy móc, thiết bị",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "2113",
    tkc: "211",
    ttk: "Phương tiện vận tải truyền dẫn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "2114",
    tkc: "211",
    ttk: "Thiết bị, dụng cụ quản lý",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "213",
    tkc: "0",
    ttk: "TSCĐ vô hình",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "2135",
    tkc: "213",
    ttk: "Chương trình phần mềm",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "214",
    tkc: "0",
    ttk: "Hao mòn tài sản cố định",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "2141",
    tkc: "214",
    ttk: "Hao mòn TSCĐ hữu hình",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "2143",
    tkc: "214",
    ttk: "Hao mòn TSCĐ vô hình",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "222",
    tkc: "0",
    ttk: "Đầu tư vào công ty liên doanh, liên kết",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "242",
    tkc: "0",
    ttk: "Chi phí trả trước",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "2421",
    tkc: "242",
    ttk: "Chi phí trả trước ngắn hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "24211",
    tkc: "2421",
    ttk: "Chi phí trả trước ngắn hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "24212",
    tkc: "2421",
    ttk: "Chi phí trả trước ngắn hạn- Giá vốn SMS Brand",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "2422",
    tkc: "242",
    ttk: "Chi phí trả trước dài hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "244",
    tkc: "0",
    ttk: "Cầm cố, thế chấp, ký quỹ, ký cược",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "2441",
    tkc: "244",
    ttk: "Cầm cố, thế chấp, ký quỹ, ký cược ngắn hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "2442",
    tkc: "244",
    ttk: "Cầm cố, thế chấp, ký quỹ, ký cược dài hạn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "331",
    tkc: "0",
    ttk: "Phải trả cho người bán",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "333",
    tkc: "0",
    ttk: "Thuế và các khoản phải nộp nhà nước",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "3331",
    tkc: "333",
    ttk: "Thuế GTGT phải nộp",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "33311",
    tkc: "3331",
    ttk: "Thuế GTGT đầu ra",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3334",
    tkc: "333",
    ttk: "Thuế thu nhập doanh nghiệp",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "3335",
    tkc: "333",
    ttk: "Thuế thu nhập cá nhân",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "3338",
    tkc: "333",
    ttk: "Thuế bảo vệ môi trường và các loại thuế khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "33382",
    tkc: "3338",
    ttk: "Các loại thuế khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3339",
    tkc: "333",
    ttk: "Phí, lệ phí và các khoản phải nộp khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "334",
    tkc: "0",
    ttk: "Phải trả người lao động",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "3341",
    tkc: "334",
    ttk: "Phải trả công nhân viên",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3348",
    tkc: "334",
    ttk: "Phải trả người lao động khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "335",
    tkc: "0",
    ttk: "Chi phí phải trả",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "338",
    tkc: "0",
    ttk: "Phải trả và phải nộp khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "3381",
    tkc: "338",
    ttk: "Phải trả và phải nộp khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3382",
    tkc: "338",
    ttk: "Kinh phí công đoàn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3383",
    tkc: "338",
    ttk: "Bảo hiểm xã hội",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3384",
    tkc: "338",
    ttk: "Bảo hiểm y tế",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3385",
    tkc: "338",
    ttk: "Phải trả tạm ứng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3386",
    tkc: "338",
    ttk: "Bảo hiểm thất nghiệp",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "3387",
    tkc: "338",
    ttk: "Doanh thu chưa thực hiện",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "341",
    tkc: "0",
    ttk: "Vay và nợ thuê tài chính",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "344",
    tkc: "0",
    ttk: "Nhận ký quỹ, ký cược",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "411",
    tkc: "0",
    ttk: "Vốn đầu tư của chủ sở hữu",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "4111",
    tkc: "411",
    ttk: "Vốn góp chủ sở hữu",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "41111",
    tkc: "4111",
    ttk: "Cổ phiếu phổ thông có quyền biểu quyết",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "421",
    tkc: "0",
    ttk: "Lợi nhuận sau thuế chưa phân phối",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "4211",
    tkc: "421",
    ttk: "Lợi nhuận sau thuế chưa phân phối năm trước",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "4212",
    tkc: "421",
    ttk: "Lợi nhuận sau thuế chưa phân phối năm nay",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "511",
    tkc: "0",
    ttk: "Doanh thu bán hàng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "5111",
    tkc: "511",
    ttk: "Doanh thu bán hàng hóa",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },

  {
    stk: "5113",
    tkc: "511",
    ttk: "Doanh thu cung cấp dịch vụ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "511301",
    tkc: "5113",
    ttk: "Doanh thu cung cấp dịch vụ khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "511302",
    tkc: "5113",
    ttk: "Doanh thu cung cấp dịch vụ ThueVP",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "515",
    tkc: "0",
    ttk: "Doanh thu hoạt động tài chính",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "5154",
    tkc: "515",
    ttk: "Lãi tiền gửi",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "5154-001",
    tkc: "5154",
    ttk: "Thu lãi tiền gửi",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "5154-002",
    tkc: "5154",
    ttk: "Thu lãi trái phiếu",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "5155",
    tkc: "515",
    ttk: "Thu lãi cho vay vốn",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "5156",
    tkc: "515",
    ttk: "Thu lãi bán ngoại tệ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "521",
    tkc: "0",
    ttk: "Các khoản giảm trừ doanh thu",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "5211",
    tkc: "521",
    ttk: "Chiết khấu thương mại",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "5213",
    tkc: "521",
    ttk: "Hàng bán bị trả lại",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "632",
    tkc: "0",
    ttk: "Giá vốn hàng bán",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "6321",
    tkc: "632",
    ttk: "Giá vốn hàng hóa",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6323",
    tkc: "632",
    ttk: "Giá vốn dịch vụ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "635",
    tkc: "0",
    ttk: "Chi phí tài chính",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "6354",
    tkc: "635",
    ttk: "Lãi tiền vay",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "6354-001",
    tkc: "6354",
    ttk: "Lãi tiền vay",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6354-002",
    tkc: "6354",
    ttk: "Lãi vay LC",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6356",
    tkc: "635",
    ttk: "Lỗ do bán ngoại tệ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "641",
    tkc: "0",
    ttk: "Chi phí bán hàng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "6411",
    tkc: "641",
    ttk: "Chi phí nhân viên",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6412",
    tkc: "641",
    ttk: "Chi phí nguyên vật liệu, bao bì",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6413",
    tkc: "641",
    ttk: "Chi phí dụng cụ, đồ dùng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6414",
    tkc: "641",
    ttk: "Chi phí khấu hao TSCĐ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "6417",
    tkc: "641",
    ttk: "Chi phí dịch vụ mua ngoài",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6418",
    tkc: "641",
    ttk: "Chi phí bằng tiền khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "642",
    tkc: "0",
    ttk: "Chi phí quản lý doanh nghiệp",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "6421",
    tkc: "642",
    ttk: "Chi phí nhân viên quản lý",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6422",
    tkc: "642",
    ttk: "Chi phí vật liệu quản lý",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6423",
    tkc: "642",
    ttk: "Chi phí đồ dùng văn phòng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6424",
    tkc: "642",
    ttk: "Chi phí khấu hao TSCĐ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6425",
    tkc: "642",
    ttk: "Thuế, phí và lệ phí",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "6427",
    tkc: "642",
    ttk: "Chi phí dịch vụ mua ngoài",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },

  {
    stk: "6428",
    tkc: "642",
    ttk: "Chi phí bằng tiền khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "711",
    tkc: "0",
    ttk: "Thu nhập khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "7111",
    tkc: "711",
    ttk: "Thu về nhượng bán, thanh lý TSCĐ",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "7112",
    tkc: "711",
    ttk: "Thu tiền được phạt vi phạm hợp đồng",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "7118",
    tkc: "711",
    ttk: "Thu nhập bất thường khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "811",
    tkc: "0",
    ttk: "Chi phí khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "8112",
    tkc: "811",
    ttk: "Chi tiền do phạt vi phạm hợp đồng",

    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "8113",
    tkc: "811",
    ttk: "Chi phạt các lĩnh vực thuế, bảo hiểm",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "8114",
    tkc: "811",
    ttk: "Phạt lãi trả chậm",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "8118",
    tkc: "811",
    ttk: "Chi phí bất thường khác",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "821",
    tkc: "0",
    ttk: "Chi phí thuế thu nhập doanh nghiệp",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
  {
    stk: "8211",
    tkc: "821",
    ttk: "Chi phí thuế TNDN hiện hành",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: false,
    isBrick: false,
  },
  {
    stk: "911",
    tkc: "0",
    ttk: "Xác định kết quả kinh doanh",
    sdk_n: "",
    sdk_c: "",
    stk_n: "",
    stk_c: "",
    sck_n: "",
    sck_c: "",
    isBold: true,
    isBrick: false,
  },
];

const B01P2 = {
  configFormatTableAsset: [
    {
      label: "A. TÀI SẢN NGẮN HẠN",
      code: "100",
      isBold: true,
      isBrick: false,
    },
    {
      label: "I. Tiền và các khoản tương đương tiền",
      code: "110",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Tiền",
      code: "111",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Các khoản tương đương tiền",
      code: "112",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },

    {
      label: "II. Đầu tư tài chính ngắn hạn",
      code: "120",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Chứng khoán kinh doanh",
      code: "121",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Dự phòng giảm giá chứng khoán kinh doanh (*)",
      code: "122",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Đầu tư nắm giữ đến ngày đáo hạn",
      code: "123",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },

    {
      label: "III. Các khoản phải thu ngắn hạn",
      code: "130",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Phải thu ngắn hạn của khách hàng",
      code: "131",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Trả trước cho người bán ngắn hạn",
      code: "132",
      isBold: false,
      isBrick: false,
    },

    {
      label: "3. Phải thu nội bộ ngắn hạn",
      code: "133",
      isBold: false,
      isBrick: false,
    },
    {
      label: "4. Phải thu theo tiến độ kế hoạch hợp đồng xây dựng",
      code: "134",
      isBold: false,
      isBrick: false,
    },
    {
      label: "5. Phải thu về cho vay ngắn hạn",
      code: "135",
      isBold: false,
      isBrick: false,
    },
    {
      label: "6. Phải thu ngắn hạn khác",
      code: "136",
      isBold: false,
      isBrick: false,
    },

    {
      label: "7. Dự phòng các khoản phải thu ngắn hạn khó đòi (*)",
      code: "137",
      isBold: false,
      isBrick: false,
    },
    {
      label: "8. Tài sản thiếu chờ xử lý",
      code: "139",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "IV. Hàng tồn kho",
      code: "140",
      isBold: true,
      isBrick: false,
    },

    {
      label: "1. Hàng tồn kho",
      code: "141",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Hàng mua đang đi trên đường",
      code: "141A",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Nguyên liệu, vật liệu tồn kho",
      code: "141B",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Công cụ, dụng cụ trong kho",
      code: "141C",
      isBold: false,
      isBrick: false,
    },

    {
      label: " - Chi phí SXKD dở dang",
      code: "141D",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Thành phẩm tồn kho",
      code: "141E",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Hàng hóa tồn kho",
      code: "141F",
      isBold: false,
      isBrick: false,
    },

    {
      label: " - Hàng hoá kho bảo thuế",
      code: "141G",
      isBold: false,
      isBrick: false,
    },

    {
      label: " - Hàng gửi đi bán",
      code: "141H",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Dự phòng giảm giá hàng tồn kho (*)",
      code: "149",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "V. Tài sản ngắn hạn khác",
      code: "150",
      isBold: true,
      isBrick: false,
    },

    {
      label: "1. Chi phi trả trước ngắn hạn",
      code: "151",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Thuế giá trị gia tăng được khấu trừ",
      code: "152",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Thuế và các khoản khác phải thu Nhà nước",
      code: "153",
      isBold: false,
      isBrick: false,
    },
    {
      label: "4. Giao dịch mua bán lại trái phiếu Chính phủ",
      code: "154",
      isBold: false,
      isBrick: false,
    },

    {
      label: "5. Tài sản ngắn hạn khác",
      code: "155",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "B. TÀI SẢN DÀI HẠN",
      code: "200",
      isBold: true,
      isBrick: false,
    },
    {
      label: "I. Các khoản phải thu dài hạn",
      code: "210",
      isBold: true,
      isBrick: false,
    },

    {
      label: "1. Phải thu dài hạn của khách hàng",
      code: "211",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Trả trước cho người bán dài hạn",
      code: "212",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Vốn kinh doanh ở công ty trực thuộc",
      code: "213",
      isBold: false,
      isBrick: false,
    },
    {
      label: "4. Phải thu nội bộ dài hạn",
      code: "214",
      isBold: false,
      isBrick: false,
    },

    {
      label: "5. Phải thu về cho vay dài hạn",
      code: "215",
      isBold: false,
      isBrick: false,
    },
    {
      label: "6. Phải thu dài hạn khác",
      code: "216",
      isBold: false,
      isBrick: false,
    },
    {
      label: "7. Dự phòng phải thu dài hạn khó đòi (*)",
      code: "219",
      isBold: false,
      isBrick: false,
    },

    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },

    {
      label: "II. Tài sản cố định",
      code: "220",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Tài sản cố định hữu hình",
      code: "221",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "222",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "223",
      isBold: false,
      isBrick: false,
    },

    {
      label: "2. Tài sản cố định thuê tài chính",
      code: "224",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "225",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "226",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Tài sản cố định vô hình",
      code: "227",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "228",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "229",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "III. Bất động sản đầu tư",
      code: "230",
      isBold: true,
      isBrick: false,
    },
    {
      label: " - Nguyên giá",
      code: "231",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - Giá trị hao mòn lũy kế (*)",
      code: "232",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "IV. Tài sản dở dang dài hạn",
      code: "240",
      isBold: true,
      isBrick: false,
    },

    {
      label: "1. Chi phí sản xuất, kinh doanh dở dang dài hạn",
      code: "241",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Chi phí xây dựng cơ bản dở dang",
      code: "242",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "V. Đầu tư tài chính dài hạn",
      code: "250",
      isBold: true,
      isBrick: false,
    },

    {
      label: "1. Đầu tư vào công ty con",
      code: "251",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Đầu tư vào công ty liên doanh, liên kết",
      code: "252",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Đầu tư góp vốn vào công ty khác",
      code: "253",
      isBold: false,
      isBrick: false,
    },
    {
      label: "4. Dự phòng đầu tư tài chính dài hạn (*)",
      code: "254",
      isBold: false,
      isBrick: false,
    },

    {
      label: "5. Đầu tư nắm giữ đến ngày đáo hạn",
      code: "255",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "VI. Tài sản dài hạn khác",
      code: "260",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Chi phí trả trước dài hạn",
      code: "261",
      isBold: false,
      isBrick: false,
    },

    {
      label: "2. Tài sản thuế thu nhập hoãn lại",
      code: "262",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Thiết bị, vật tư, phụ tùng thay thế dài hạn",
      code: "263",
      isBold: false,
      isBrick: false,
    },
    {
      label: "4. Tài sản dài hạn khác",
      code: "268",
      isBold: false,
      isBrick: false,
    },
    {
      label: "TỔNG CỘNG TÀI SẢN (270 = 100 + 200)",
      code: "270",
      isBold: true,
      isBrick: false,
    },
  ],

  configFormatTableInvestment: [
    {
      label: "C. NỢ PHẢI TRẢ",
      code: "300",
      isBold: true,
      isBrick: false,
    },
    {
      label: "I. Nợ ngắn hạn",
      code: "310",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Phải trả người bán ngắn hạn",
      code: "311",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Người mua trả tiền trước ngắn hạn",
      code: "312",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Thuế và các khoản phải nộp nhà nước",
      code: "313",
      isBold: false,
      isBrick: false,
    },

    {
      label: "4. Phải trả người lao động",
      code: "314",
      isBold: false,
      isBrick: false,
    },
    {
      label: "5. Chi phí phải trả ngắn hạn",
      code: "315",
      isBold: false,
      isBrick: false,
    },
    {
      label: "6. Phải trả nội bộ ngắn hạn",
      code: "316",
      isBold: false,
      isBrick: false,
    },
    {
      label: "7. Phải trả theo tiến độ kế hoạch hợp đồng xây dựng",
      code: "317",
      isBold: false,
      isBrick: false,
    },
    {
      label: "8. Doanh thu chưa thực hiện ngắn hạn",
      code: "318",
      isBold: false,
      isBrick: false,
    },
    {
      label: "9. Phải trả ngắn hạn khác",
      code: "319",
      isBold: false,
      isBrick: false,
    },
    {
      label: "10. Vay và nợ thuê tài chính ngắn hạn",
      code: "320",
      isBold: false,
      isBrick: false,
    },
    {
      label: "11. Dự phòng phải trả ngắn hạn",
      code: "321",
      isBold: false,
      isBrick: false,
    },
    {
      label: "12. Quỹ khen thưởng, phúc lợi",
      code: "322",
      isBold: false,
      isBrick: false,
    },
    {
      label: "13. Quỹ bình ổn giá",
      code: "323",
      isBold: false,
      isBrick: false,
    },

    {
      label: "14. Giao dịch mua bán lại trái phiếu Chính phủ",
      code: "324",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "II. Nợ dài hạn",
      code: "330",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Phải trả người bán dài hạn",
      code: "331",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Người mua trả tiền trước dài hạn",
      code: "332",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Chi phí phải trả dài hạn",
      code: "333",
      isBold: false,
      isBrick: false,
    },
    {
      label: "4. Phải trả nội bộ về vốn kinh doanh",
      code: "334",
      isBold: false,
      isBrick: false,
    },
    {
      label: "5. Phải trả nội bộ dài hạn",
      code: "335",
      isBold: false,
      isBrick: false,
    },
    {
      label: "6. Doanh thu chưa thực hiện dài hạn",
      code: "336",
      isBold: false,
      isBrick: false,
    },
    {
      label: "7. Phải trả dài hạn khác",
      code: "337",
      isBold: false,
      isBrick: false,
    },

    {
      label: "8. Vay và nợ thuê tài chính dài hạn",
      code: "338",
      isBold: false,
      isBrick: false,
    },
    {
      label: "9. Trái phiếu chuyển đổi",
      code: "339",
      isBold: false,
      isBrick: false,
    },
    {
      label: "10. Cổ phiếu ưu đãi",
      code: "340",
      isBold: false,
      isBrick: false,
    },
    {
      label: "11. Thuế thu nhập hoãn lại phải trả",
      code: "341",
      isBold: false,
      isBrick: false,
    },
    {
      label: "12. Dự phòng phải trả dài hạn",
      code: "342",
      isBold: false,
      isBrick: false,
    },
    {
      label: "13. Quỹ phát triển khoa học, công nghệ",
      code: "343",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "D. VỐN CHỦ SỞ HỮU",
      code: "400",
      isBold: true,
      isBrick: false,
    },
    {
      label: "I. Vốn chủ sở hữu",
      code: "410",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Vốn góp của chủ sở hữu",
      code: "411",
      isBold: false,
      isBrick: false,
    },

    {
      label: "- Cổ phiếu phổ thông có quyền biểu quyết",
      code: "411a",
      isBold: false,
      isBrick: false,
    },
    {
      label: "- Cổ phiếu ưu đãi",
      code: "411b",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Thặng dư vốn cổ phần",
      code: "412",
      isBold: false,
      isBrick: false,
    },
    {
      label: "3. Quyền chọn chuyển đổi trái phiếu",
      code: "413",
      isBold: false,
      isBrick: false,
    },
    {
      label: "4. Vốn khác của chủ sở hữu",
      code: "414",
      isBold: false,
      isBrick: false,
    },
    {
      label: "5. Cổ phiếu quỹ (*)",
      code: "415",
      isBold: false,
      isBrick: false,
    },
    {
      label: "6. Chênh lệch đánh giá lại tài sản",
      code: "416",
      isBold: false,
      isBrick: false,
    },
    {
      label: "7. Chênh lệch tỷ giá hối đoái",
      code: "417",
      isBold: false,
      isBrick: false,
    },
    {
      label: "8. Quỹ đầu tư phát triển",
      code: "418",
      isBold: false,
      isBrick: false,
    },
    {
      label: "9. Quỹ hỗ trợ sắp xếp doanh nghiệp",
      code: "419",
      isBold: false,
      isBrick: false,
    },

    {
      label: "10. Quỹ khác thuộc vốn chủ sở hữu",
      code: "420",
      isBold: false,
      isBrick: false,
    },
    {
      label: "11. Lợi nhuận sau thuế chưa phân phối",
      code: "421",
      isBold: false,
      isBrick: false,
    },
    {
      label: "- LNST chưa phân phối lũy kế đến cuối kỳ trước",
      code: "421a",
      isBold: false,
      isBrick: false,
    },
    {
      label: " - LNST chưa phân phối kỳ này",
      code: "421b",
      isBold: false,
      isBrick: false,
    },
    {
      label: "12. Nguồn vốn đầu tư XDCB",
      code: "422",
      isBold: false,
      isBrick: false,
    },
    {
      label: "",
      code: "",
      isBold: false,
      isBrick: true,
    },
    {
      label: "II. Nguồn kinh phí và quỹ khác",
      code: "430",
      isBold: true,
      isBrick: false,
    },
    {
      label: "1. Nguồn kinh phí",
      code: "431",
      isBold: false,
      isBrick: false,
    },
    {
      label: "2. Nguồn kinh phí đã hình thành TSCĐ",
      code: "432",
      isBold: false,
      isBrick: false,
    },
    {
      label: "TỔNG CỘNG NGUỒN VỐN (440 = 300 + 400)",
      code: "440",
      isBold: true,
      isBrick: false,
    },
  ],
};

const B03 = [
  {
    label: "I. Lưu chuyển tiền từ hoạt động kinh doanh",
    code: "",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "1. Lợi nhuận trước thuế",
    code: "01",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "2. Điều chỉnh cho các khoản",
    code: "",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Khấu hao TSCĐ và BĐSĐT",
    code: "02",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Các khoản dự phòng",
    code: "03",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label:
      "- Lãi, lỗ chênh lệch tỷ giá hối đoái do đánh giá lại Các khoản mục tiền tệ có gốc ngoại tệ",
    code: "04",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Lãi, lỗ từ hoạt động đầu tư",
    code: "05",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Các khoản điều chỉnh khác",
    code: "07",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "3. Lợi nhuận kinh doanh trước thay đổi vốn lưu động",
    code: "08",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Tăng, giảm Các khoản phải thu",
    code: "09",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Tăng, giảm hàng tồn kho",
    code: "10",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label:
      "- Tăng, giảm Các khoản phải trả (không kể Lãi vay phải trả, thuế thu nhập phải nộp)",
    code: "11",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Tăng, giảm chi phí trả trước",
    code: "12",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- Tăng, giảm chứng khoán kinh doanh",
    code: "13",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- tiền Lãi vay đã trả",
    code: "14",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- thuế thu nhập doanh nghiệp đã nộp",
    code: "15",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- tiền thu khác từ hoạt động kinh doanh",
    code: "16",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "- tiền chi khác từ hoạt động kinh doanh",
    code: "17",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "Lưu chuyển tiền thuần từ hoạt động kinh doanh",
    code: "20",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "II. Lưu chuyển tiền từ hoạt động đầu tư",
    code: "",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "1. Tiền chi để mua sắm, xây dựng TSCĐ và các TS dài hạn khác",
    code: "21",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label:
      "2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác",
    code: "22",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "3. Tiền chi cho vay, mua các công cụ nợ của công ty khác",
    code: "23",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "4. Tiền thu hồi cho vay, bán lại các công cụ nợ của công ty khác",
    code: "24",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "5. Tiền chi đầu tư góp vốn vào công ty khác",
    code: "25",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "6. Tiền thu hồi đầu tư góp vốn vào công ty khác",
    code: "26",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia",
    code: "27",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "Lưu chuyển tiền thuần từ hoạt động đầu tư",
    code: "30",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "III. Lưu chuyển tiền từ hoạt động tài chính",
    code: "",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "1. Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu",
    code: "31",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label:
      "2. Tiền chi trả vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành",
    code: "32",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "3. Tiền thu từ đi vay",
    code: "33",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "4. Tiền chi trả nợ gốc vay",
    code: "34",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "5. Tiền chi trả nợ thuê tài chính",
    code: "35",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "6. Cổ tức, lợi nhuận đã trả cho chủ sở hữu",
    code: "36",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "Lưu chuyển tiền thuần từ hoạt động tài chính",
    code: "40",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "Lưu chuyển tiền thuần trong kỳ (50=20+30+40)",
    code: "50",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "Tiền và tương đương tiền đầu kỳ",
    code: "60",
    isBold: true,
    tm: "",
    isBrick: false,
  },
  {
    label: "Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ",
    code: "61",
    isBold: false,
    tm: "",
    isBrick: false,
  },
  {
    label: "Tiền và tương đương tiền cuối kỳ (70=50+60+61)",
    code: "70",
    isBold: true,
    tm: "",
    isBrick: false,
  },
];

export { B01, B02, S06, B01P2, B03 };
